#Aplications Configuration
server:
  port: 8093
  error:
    include-message: always
  include-binding-errors: always

#Enabling h2 Console
spring:
  h2:
    console:
      enable: true

      #===================
      #BD
      #===================
      datasource:
        url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        dirverClassName: org.h2.Driver
        plataform: h2
        username: sa
        password:

      #====================
      #JPA / HIBERNATE
      #===================
      jpa:
        show-sql: true
        hibernate:
          ddl-auto:update
        database-plataform: org.hibernate.dialect.H2Dialect
        properties:
          hibernate:
            show_sql: true
            use_sql_comments: false
            format_sql: false
loggin:
  pattern:
    console:"%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"



